// protoc -I api/proto/ --go_out=types --go_opt=paths=source_relative --go-grpc_out=types --go-grpc_opt=paths=source_relative pro.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: pro.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SinxPro_ACLPolicyUpsert_FullMethodName = "/types.SinxPro/ACLPolicyUpsert"
	SinxPro_ACLPolicyDelete_FullMethodName = "/types.SinxPro/ACLPolicyDelete"
	SinxPro_ACLPolicyInfo_FullMethodName   = "/types.SinxPro/ACLPolicyInfo"
	SinxPro_ACLPolicyList_FullMethodName   = "/types.SinxPro/ACLPolicyList"
	SinxPro_ACLTokenUpsert_FullMethodName  = "/types.SinxPro/ACLTokenUpsert"
	SinxPro_ACLTokenDelete_FullMethodName  = "/types.SinxPro/ACLTokenDelete"
	SinxPro_ACLTokenInfo_FullMethodName    = "/types.SinxPro/ACLTokenInfo"
	SinxPro_ACLTokenList_FullMethodName    = "/types.SinxPro/ACLTokenList"
)

// SinxProClient is the client API for SinxPro service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DkronPro is the DkronPro service definition
type SinxProClient interface {
	ACLPolicyUpsert(ctx context.Context, in *ACLPolicyUpsertRequest, opts ...grpc.CallOption) (*ACLPolicyUpsertResponse, error)
	ACLPolicyDelete(ctx context.Context, in *ACLPolicyDeleteRequest, opts ...grpc.CallOption) (*ACLPolicyDeleteResponse, error)
	ACLPolicyInfo(ctx context.Context, in *ACLPolicyInfoRequest, opts ...grpc.CallOption) (*ACLPolicyInfoResponse, error)
	ACLPolicyList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ACLPolicyListResponse, error)
	ACLTokenUpsert(ctx context.Context, in *ACLTokenUpsertRequest, opts ...grpc.CallOption) (*ACLTokenUpsertResponse, error)
	ACLTokenDelete(ctx context.Context, in *ACLTokenDeleteRequest, opts ...grpc.CallOption) (*ACLTokenDeleteResponse, error)
	ACLTokenInfo(ctx context.Context, in *ACLTokenInfoRequest, opts ...grpc.CallOption) (*ACLTokenInfoResponse, error)
	ACLTokenList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ACLTokenListResponse, error)
}

type sinxProClient struct {
	cc grpc.ClientConnInterface
}

func NewSinxProClient(cc grpc.ClientConnInterface) SinxProClient {
	return &sinxProClient{cc}
}

func (c *sinxProClient) ACLPolicyUpsert(ctx context.Context, in *ACLPolicyUpsertRequest, opts ...grpc.CallOption) (*ACLPolicyUpsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACLPolicyUpsertResponse)
	err := c.cc.Invoke(ctx, SinxPro_ACLPolicyUpsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinxProClient) ACLPolicyDelete(ctx context.Context, in *ACLPolicyDeleteRequest, opts ...grpc.CallOption) (*ACLPolicyDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACLPolicyDeleteResponse)
	err := c.cc.Invoke(ctx, SinxPro_ACLPolicyDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinxProClient) ACLPolicyInfo(ctx context.Context, in *ACLPolicyInfoRequest, opts ...grpc.CallOption) (*ACLPolicyInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACLPolicyInfoResponse)
	err := c.cc.Invoke(ctx, SinxPro_ACLPolicyInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinxProClient) ACLPolicyList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ACLPolicyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACLPolicyListResponse)
	err := c.cc.Invoke(ctx, SinxPro_ACLPolicyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinxProClient) ACLTokenUpsert(ctx context.Context, in *ACLTokenUpsertRequest, opts ...grpc.CallOption) (*ACLTokenUpsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACLTokenUpsertResponse)
	err := c.cc.Invoke(ctx, SinxPro_ACLTokenUpsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinxProClient) ACLTokenDelete(ctx context.Context, in *ACLTokenDeleteRequest, opts ...grpc.CallOption) (*ACLTokenDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACLTokenDeleteResponse)
	err := c.cc.Invoke(ctx, SinxPro_ACLTokenDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinxProClient) ACLTokenInfo(ctx context.Context, in *ACLTokenInfoRequest, opts ...grpc.CallOption) (*ACLTokenInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACLTokenInfoResponse)
	err := c.cc.Invoke(ctx, SinxPro_ACLTokenInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinxProClient) ACLTokenList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ACLTokenListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACLTokenListResponse)
	err := c.cc.Invoke(ctx, SinxPro_ACLTokenList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SinxProServer is the server API for SinxPro service.
// All implementations must embed UnimplementedSinxProServer
// for forward compatibility.
//
// DkronPro is the DkronPro service definition
type SinxProServer interface {
	ACLPolicyUpsert(context.Context, *ACLPolicyUpsertRequest) (*ACLPolicyUpsertResponse, error)
	ACLPolicyDelete(context.Context, *ACLPolicyDeleteRequest) (*ACLPolicyDeleteResponse, error)
	ACLPolicyInfo(context.Context, *ACLPolicyInfoRequest) (*ACLPolicyInfoResponse, error)
	ACLPolicyList(context.Context, *emptypb.Empty) (*ACLPolicyListResponse, error)
	ACLTokenUpsert(context.Context, *ACLTokenUpsertRequest) (*ACLTokenUpsertResponse, error)
	ACLTokenDelete(context.Context, *ACLTokenDeleteRequest) (*ACLTokenDeleteResponse, error)
	ACLTokenInfo(context.Context, *ACLTokenInfoRequest) (*ACLTokenInfoResponse, error)
	ACLTokenList(context.Context, *emptypb.Empty) (*ACLTokenListResponse, error)
	mustEmbedUnimplementedSinxProServer()
}

// UnimplementedSinxProServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSinxProServer struct{}

func (UnimplementedSinxProServer) ACLPolicyUpsert(context.Context, *ACLPolicyUpsertRequest) (*ACLPolicyUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ACLPolicyUpsert not implemented")
}
func (UnimplementedSinxProServer) ACLPolicyDelete(context.Context, *ACLPolicyDeleteRequest) (*ACLPolicyDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ACLPolicyDelete not implemented")
}
func (UnimplementedSinxProServer) ACLPolicyInfo(context.Context, *ACLPolicyInfoRequest) (*ACLPolicyInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ACLPolicyInfo not implemented")
}
func (UnimplementedSinxProServer) ACLPolicyList(context.Context, *emptypb.Empty) (*ACLPolicyListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ACLPolicyList not implemented")
}
func (UnimplementedSinxProServer) ACLTokenUpsert(context.Context, *ACLTokenUpsertRequest) (*ACLTokenUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ACLTokenUpsert not implemented")
}
func (UnimplementedSinxProServer) ACLTokenDelete(context.Context, *ACLTokenDeleteRequest) (*ACLTokenDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ACLTokenDelete not implemented")
}
func (UnimplementedSinxProServer) ACLTokenInfo(context.Context, *ACLTokenInfoRequest) (*ACLTokenInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ACLTokenInfo not implemented")
}
func (UnimplementedSinxProServer) ACLTokenList(context.Context, *emptypb.Empty) (*ACLTokenListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ACLTokenList not implemented")
}
func (UnimplementedSinxProServer) mustEmbedUnimplementedSinxProServer() {}
func (UnimplementedSinxProServer) testEmbeddedByValue()                 {}

// UnsafeSinxProServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SinxProServer will
// result in compilation errors.
type UnsafeSinxProServer interface {
	mustEmbedUnimplementedSinxProServer()
}

func RegisterSinxProServer(s grpc.ServiceRegistrar, srv SinxProServer) {
	// If the following call pancis, it indicates UnimplementedSinxProServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SinxPro_ServiceDesc, srv)
}

func _SinxPro_ACLPolicyUpsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACLPolicyUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinxProServer).ACLPolicyUpsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinxPro_ACLPolicyUpsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinxProServer).ACLPolicyUpsert(ctx, req.(*ACLPolicyUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinxPro_ACLPolicyDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACLPolicyDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinxProServer).ACLPolicyDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinxPro_ACLPolicyDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinxProServer).ACLPolicyDelete(ctx, req.(*ACLPolicyDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinxPro_ACLPolicyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACLPolicyInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinxProServer).ACLPolicyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinxPro_ACLPolicyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinxProServer).ACLPolicyInfo(ctx, req.(*ACLPolicyInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinxPro_ACLPolicyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinxProServer).ACLPolicyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinxPro_ACLPolicyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinxProServer).ACLPolicyList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinxPro_ACLTokenUpsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACLTokenUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinxProServer).ACLTokenUpsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinxPro_ACLTokenUpsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinxProServer).ACLTokenUpsert(ctx, req.(*ACLTokenUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinxPro_ACLTokenDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACLTokenDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinxProServer).ACLTokenDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinxPro_ACLTokenDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinxProServer).ACLTokenDelete(ctx, req.(*ACLTokenDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinxPro_ACLTokenInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACLTokenInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinxProServer).ACLTokenInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinxPro_ACLTokenInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinxProServer).ACLTokenInfo(ctx, req.(*ACLTokenInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinxPro_ACLTokenList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinxProServer).ACLTokenList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinxPro_ACLTokenList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinxProServer).ACLTokenList(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SinxPro_ServiceDesc is the grpc.ServiceDesc for SinxPro service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SinxPro_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "types.SinxPro",
	HandlerType: (*SinxProServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ACLPolicyUpsert",
			Handler:    _SinxPro_ACLPolicyUpsert_Handler,
		},
		{
			MethodName: "ACLPolicyDelete",
			Handler:    _SinxPro_ACLPolicyDelete_Handler,
		},
		{
			MethodName: "ACLPolicyInfo",
			Handler:    _SinxPro_ACLPolicyInfo_Handler,
		},
		{
			MethodName: "ACLPolicyList",
			Handler:    _SinxPro_ACLPolicyList_Handler,
		},
		{
			MethodName: "ACLTokenUpsert",
			Handler:    _SinxPro_ACLTokenUpsert_Handler,
		},
		{
			MethodName: "ACLTokenDelete",
			Handler:    _SinxPro_ACLTokenDelete_Handler,
		},
		{
			MethodName: "ACLTokenInfo",
			Handler:    _SinxPro_ACLTokenInfo_Handler,
		},
		{
			MethodName: "ACLTokenList",
			Handler:    _SinxPro_ACLTokenList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pro.proto",
}
